---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: bullseye64
    box: debian/bullseye64
    memory: 512
    cpus: 2
  - name: buster64
    box: debian/buster64
    memory: 512
    cpus: 2
lint: yamllint .
provisioner:
  name: ansible
  become: true
